import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

const root = fileURLToPath(new URL('../../', import.meta.url));
const labels = {
  PK: 'pk', MERKLE: 'merkle', TREASURY_NOTE: 'treasury-note', PRIVATE_NOTE: 'private-note',
  FINAL_NOTE: 'final-note', NOTE_NULLIFIER: 'note-nullifier', ALLOCATION: 'allocation',
  DISTRIBUTION: 'distribution', CLAIM_NULLIFIER: 'claim-nullifier', AUTH_POLICY: 'auth-policy',
  AUTH_INTENT: 'auth-intent', NOTE_OWNER: 'note-owner', NOTE_SECRET: 'note-secret',
  CLAIM_INTENT: 'claim-intent', PHANTOM_NULLIFIER: 'phantom-nullifier', WITHDRAW_INTENT: 'withdraw-intent',
};
const domains = Object.fromEntries(Object.entries(labels).map(([key, suffix]) => {
  const bytes = createHash('sha256').update(`null.v1.${suffix}`).digest().subarray(0, 31);
  return [key, BigInt(`0x${bytes.toString('hex')}`).toString()];
}));
writeFileSync(resolve(root, 'contracts/src/libraries/Domains.sol'),
  '// SPDX-License-Identifier: MIT\npragma solidity 0.8.28;\n\n// Generated by contracts/scripts/generate-domains.mjs. Do not edit.\nlibrary Domains {\n' +
  Object.entries(domains).map(([name, value]) => `    uint256 internal constant ${name} = ${value};`).join('\n') + '\n}\n');
writeFileSync(resolve(root, 'circuits/lib/src/domains.nr'),
  '// Generated by contracts/scripts/generate-domains.mjs. Do not edit.\n' +
  Object.entries(domains).map(([name, value]) => `pub global ${name}: Field = ${value};`).join('\n') + '\n');
writeFileSync(resolve(root, 'circuits/domains.json'), `${JSON.stringify(domains, null, 2)}\n`);
