import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {authPolicyCommitment,prepareWithdrawalIntent,buildWithdrawalWitness,privateNoteBody,treasuryNoteBody,finalNoteCommitment,IncrementalMerkleTree,toHex,fromHex,bigintToBytes,secp256k1,fieldHex} from './index';
import {validateWithdrawalIntent,createPrivyAuthorizationRequest} from '../../auth/src/index';
import {validateRelayPayload} from '../../../services/relayer/src/relay';
const context={chainId:11155111n,poolAddress:'0x0000000000000000000000000000000000000123' as const};
const recipient='0x0000000000000000000000000000000000000456' as const;
const signer=bigintToBytes(71n),policy={signerPublicKey:toHex(secp256k1.getPublicKey(signer,true)),policyMetadata:9n,registrationBlinder:11n};
const authTree=new IncrementalMerkleTree(20,[authPolicyCommitment(policy)]);
const amountAtomic=600_000n, ownerNullifierKey=72n,noteSecret=73n;
function options(treasury=false){const body=treasury?treasuryNoteBody(ownerNullifierKey,authPolicyCommitment(policy),amountAtomic,noteSecret):privateNoteBody(ownerNullifierKey,amountAtomic,noteSecret);const tree=new IncrementalMerkleTree(20,[finalNoteCommitment(body,0)]);return {context,recipient,note:{ownerNullifierKey,noteSecret,amountAtomic,path:tree.getPath(0)},authRoot:authTree.root,nonce:74n,validUntil:BigInt(Math.floor(Date.now()/1000)+3600),...(treasury?{authPolicy:policy,policyPath:authTree.getPath(0)}:{})};}
test('private withdrawal binds amount and original note path',()=>{const base=options();const built=buildWithdrawalWitness(base);assert.equal(built.publicInputs.length,10);assert.equal(BigInt(built.publicInputs[7]),amountAtomic);assert.throws(()=>buildWithdrawalWitness({...base,note:{...base.note,amountAtomic:amountAtomic+1n}}));assert.throws(()=>buildWithdrawalWitness({...base,note:{...base.note,ownerNullifierKey:99n}}));});
test('withdrawal rejects zero, oversized and pool destinations',()=>{for(const recipient of ['0x'+'0'.repeat(40),context.poolAddress,'0x'+'1'.repeat(42)])assert.throws(()=>buildWithdrawalWitness({...options(),recipient:recipient as `0x${string}`}));});
test('treasury withdrawal requires exact organization signature',()=>{const base=options(true);assert.throws(()=>buildWithdrawalWitness(base));const intent=prepareWithdrawalIntent(base);const signerSignature=toHex(secp256k1.sign(fromHex(intent.digest),signer,{prehash:false,lowS:true}).toCompactRawBytes());assert.doesNotThrow(()=>buildWithdrawalWitness({...base,signerSignature}));assert.throws(()=>buildWithdrawalWitness({...base,recipient:'0x0000000000000000000000000000000000000789',signerSignature}));assert.throws(()=>buildWithdrawalWitness({...base,nonce:75n,signerSignature}));});
test('Privy withdrawal intent rejects destination, amount, chain and expiry changes',async()=>{const base=options(true),built=prepareWithdrawalIntent(base),expected={...context,kind:'withdrawal' as const,recipient,amountAtomic};validateWithdrawalIntent(built.publicInputs,expected);for(const index of [1,2,6,7]){const changed=[...built.publicInputs];changed[index]=fieldHex(BigInt(changed[index])+1n);assert.throws(()=>validateWithdrawalIntent(changed,expected));}const expired=[...built.publicInputs];expired[9]=fieldHex(1n);assert.throws(()=>validateWithdrawalIntent(expired,expected));const request=await createPrivyAuthorizationRequest({appId:'app',walletId:'wallet',publicInputs:built.publicInputs,expected});assert.equal(request.body.params.hash,built.digest);});
test('withdrawal relay accepts only public proof fields',()=>{const built=prepareWithdrawalIntent(options());const payload={chainId:11155111,pool:context.poolAddress,method:'withdraw',proof:'0x'+'ab'.repeat(64),publicInputs:built.publicInputs};assert.equal(validateRelayPayload(payload).method,'withdraw');assert.throws(()=>validateRelayPayload({...payload,witness:built.witness}));assert.throws(()=>validateRelayPayload({...payload,envelopes:[]}));assert.throws(()=>validateRelayPayload({...payload,publicInputs:built.publicInputs.slice(1)}));});
test('real withdrawal circuit accepts private and approved treasury witnesses',async()=>{const require=createRequire(new URL('../../prover/package.json',import.meta.url));const {Noir}=require('@noir-lang/noir_js');const circuit=JSON.parse(await readFile(new URL('../../../circuits/target/withdraw.json',import.meta.url),'utf8'));for(const treasury of [false,true]){const base=options(treasury),intent=prepareWithdrawalIntent(base);const built=buildWithdrawalWitness({...base,...(treasury?{signerSignature:toHex(secp256k1.sign(fromHex(intent.digest),signer,{prehash:false,lowS:true}).toCompactRawBytes())}:{})});const execution=await new Noir(circuit).execute(built.witness);execution.witness.fill(0);const mutated=structuredClone(built.witness);mutated.owner_nullifier_key='999';await assert.rejects(()=>new Noir(circuit).execute(mutated));}});
