import { useState } from 'react';
import { ArrowRight, Copy, Download, KeyRound, LogOut } from 'lucide-react';
import { useAccount } from '../lib/account';
import { useSession } from '../lib/session';
import { useStore } from '../lib/store';
import { config } from '../lib/config';
import { Button, KeyValue, Modal, Notice, PageHeader } from './ui';
import { Recovery } from './Recovery';

export function AccountSettings() {
  const store = useStore(); const account = useAccount(); const session = useSession();
  const [name, setName] = useState(store.organization); const [error, setError] = useState('');
  const [recovery, setRecovery] = useState<'export' | 'restore' | null>(null); const [leaving, setLeaving] = useState(false);
  const organization = account.profile?.type === 'organization';
  return <><PageHeader title="Settings" description="Manage your account and backups." />
    <div className="settings-sections">
      <section className="settings-section"><div className="settings-description"><h2>Account</h2><p>Choose how you use NULL.</p></div><div className="settings-fields"><div className="detail-list"><KeyValue label="Signed in as">{session.label}</KeyValue><KeyValue label="Account type">{organization ? 'Organization' : 'Individual'}</KeyValue></div><Button variant="secondary" onClick={account.changeAccountType}>Change account type</Button><p className="field-hint">Your choice is saved in this browser. You can switch without signing out.</p></div></section>
      {organization && <section className="settings-section"><div className="settings-description"><h2>Organization</h2><p>The name shown on your account.</p></div><form className="settings-fields" onSubmit={event => { event.preventDefault(); if (!name.trim()) { setError('Enter an organization name.'); return; } account.updateProfile({ type: 'organization', organizationName: name.trim() }); store.setOrganization(name.trim()); store.toast('Organization name saved.'); setError(''); }}><label className="field">Organization name<input autoComplete="organization" value={name} maxLength={50} required onChange={event => setName(event.target.value)} /></label><Button type="submit" variant="secondary">Save name</Button>{error && <p className="form-error" role="alert">{error}</p>}<p className="field-hint">This name is for display. Your organization must approve your access before you can send for it.</p></form></section>}
      {!organization && <section className="settings-section"><div className="settings-description"><h2>Payment ID</h2><p>Share this with someone who wants to pay you.</p></div><div className="settings-fields"><label className="field">Your Payment ID<textarea rows={3} value={store.identity.profile.stealthMetaAddress} readOnly className="mono-input" /><small>This is public. It is not a wallet address.</small></label><div className="button-row"><Button variant="secondary" icon={Copy} onClick={async () => { try { await navigator.clipboard.writeText(store.identity.profile.stealthMetaAddress); store.toast('Payment ID copied.'); } catch { store.toast('Select your Payment ID and copy it manually.'); } }}>Copy Payment ID</Button></div></div></section>}
      <section className="settings-section"><div className="settings-description"><h2>Payment ID backup</h2><p>Keep access when you come back.</p></div><div className="settings-fields"><div className="recovery-setting"><span><KeyRound size={22} /></span><div><strong>Save a backup before leaving.</strong><p>Signing in alone will not restore your Payment ID. Funds backups are separate, under Restore balance.</p></div></div><div className="button-row"><Button variant="secondary" icon={Download} onClick={() => setRecovery('export')}>Save backup</Button><Button variant="ghost" onClick={() => setRecovery('restore')}>Restore backup</Button></div></div></section>
      <section className="settings-section"><div className="settings-description"><h2>Display</h2><p>Choose what others can see on your screen.</p></div><div className="settings-fields"><label className="toggle-row"><div><strong>Hide balances</strong><p>Hide your balance when sharing your screen.</p></div><input className="toggle" type="checkbox" role="switch" checked={store.hideBalances} onChange={event => store.setHideBalances(event.target.checked)} /></label><p className="field-hint">Payment forms and downloaded files still show amounts.</p></div></section>
      <details className="progressive-details"><summary>Advanced settings</summary><div className="settings-fields"><KeyValue label="Network">Ethereum Sepolia</KeyValue><p className="field-hint">Payments always use Sepolia test tokens, with no real money.</p><h3>Connection setup</h3><div className="detail-list"><KeyValue label="Sign-in">{config.privyAppId ? 'Set up' : 'Not set up'}</KeyValue><KeyValue label="Payments">{config.poolAddress ? 'Set up' : 'Not set up'}</KeyValue><KeyValue label="Payment lookup">{config.graphUrl ? 'Set up' : 'Not set up'}</KeyValue><KeyValue label="Payment delivery">{config.relayerUrl ? 'Set up' : 'Not set up'}</KeyValue></div><p className="field-hint">These show what has been set up, not whether each service is currently working.</p><Button variant="secondary" onClick={() => store.navigate('protocol')}>Check connection details<ArrowRight size={15} /></Button></div></details>
      <section className="settings-section"><div className="settings-description"><h2>Sign out</h2><p>End this session on this device.</p></div><div className="settings-fields"><Button variant="secondary" icon={LogOut} onClick={() => setLeaving(true)}>Sign out</Button>{session.error && <p className="form-error" role="alert">{session.error}</p>}</div></section>
    </div>
    <Modal open={leaving} title="Sign out?" description="Save a backup so you can come back." onClose={() => { if (!session.signingOut) setLeaving(false); }}><Notice tone="warning">Signing out clears the drafts from this session and your access to this Payment ID. Keep a backup and its password to restore access. Signing in alone will not restore it.</Notice>{session.error && <p className="form-error" role="alert">{session.error}</p>}<div className="modal-actions"><Button variant="secondary" disabled={session.signingOut} onClick={() => { setLeaving(false); setRecovery('export'); }}>Save backup</Button><Button busy={session.signingOut} icon={LogOut} onClick={() => void session.signOut()}>Sign out</Button></div></Modal>
    <Recovery key={recovery || 'closed'} open={recovery !== null} initialMode={recovery || 'export'} onClose={() => setRecovery(null)} />
  </>;
}
