import { ArrowRight, Check, CheckCircle2, LockKeyhole, ShieldCheck } from 'lucide-react';
import { paymentProgress, paymentSteps, type PaymentProgressInput } from '../lib/payment-progress';

export type PaymentProgressProps = {
  state: PaymentProgressInput; amount: string; from: string; to: string; kind: 'create_distribution' | 'shield' | 'claim' | 'withdraw';
  recipients?: { name: string; amount: string }[]; cre?: boolean; gasWallet?: string; batch?: string;
};
export function PaymentProgress({ state, amount, from, to, kind, recipients, cre, gasWallet, batch }: PaymentProgressProps) {
  const progress = paymentProgress(state);
  const title = state.confirmed && kind === 'claim' ? 'Collected into your private balance' : state.confirmed && kind === 'withdraw' ? 'USDC sent to your wallet' : state.confirmed && kind === 'shield' ? 'USDC added to the pool' : kind === 'claim' && progress.index === 1 ? 'Prepare to collect' : kind === 'withdraw' && progress.index === 1 ? 'Choose your withdrawal' : kind === 'shield' && progress.index === 1 ? 'Choose your funding wallet' : progress.title;
  const body = state.confirmed && kind === 'claim' ? 'Your payment is now available in NULL. USDC stays in the pool until you choose Balance → Withdraw to move it to your wallet.'
    : state.confirmed && kind === 'withdraw' ? 'USDC moved from the pool to the receiving wallet. This amount and destination are visible on Sepolia.'
    : state.confirmed && kind === 'shield' ? 'USDC moved from your funding wallet into the pool. It is now available for private payments.'
    : kind === 'claim' && progress.index === 1 ? 'Collecting adds this payment to your private NULL balance. USDC stays in the pool; withdrawing to your wallet is a separate step.'
    : kind === 'withdraw' && progress.index === 1 ? 'Choose the note and confirm its receiving wallet. The withdrawal amount and destination will be public.'
    : kind === 'shield' && progress.index === 1 ? 'Your wallet, deposit amount and timing will be public. Private payouts are a separate step.' : progress.body;
  const steps = paymentSteps.map((step, index) => kind !== 'create_distribution' && index === 1 ? 'Choose wallet' : kind === 'claim' && index === 2 ? 'Create proof' : step);
  return <section className="payment-journey" aria-label="Payment progress">
    <div className="payment-journey-summary"><span className="payment-amount">{amount}<small>test USDC</small></span><span className={`payment-privacy ${kind === 'withdraw' || kind === 'shield' ? 'is-public' : ''}`}>{state.confirmed ? <CheckCircle2 size={16} /> : <LockKeyhole size={16} />}{state.confirmed ? 'Confirmed on Sepolia' : kind === 'withdraw' ? 'Public withdrawal' : kind === 'shield' ? 'Public deposit' : 'Private allocation'}</span></div>
    <div className="payment-route"><div><span>From</span><bdi>{from}</bdi></div><ArrowRight className="payment-route-arrow" size={21} aria-hidden="true" /><div><span>To</span><bdi>{to}</bdi></div></div>
    {kind === 'claim' && <p className="payment-location">Destination: your private NULL balance. Collecting does not transfer USDC to MetaMask.</p>}
    {kind === 'create_distribution' && cre && <p className="payment-location"><Check size={14} aria-hidden="true" />Chainlink CRE checked this batch · local simulation</p>}
    {recipients && recipients.length > 1 && <details className="payment-recipients"><summary>View {recipients.length} recipients</summary><ul>{recipients.map((recipient, index) => <li key={`${recipient.name}-${index}`}><bdi>{recipient.name}</bdi><span>{recipient.amount} USDC</span></li>)}</ul></details>}
    <ol className="payment-steps" aria-label="Transaction steps">{steps.map((step, index) => <li key={step} className={index < progress.index || state.confirmed ? 'is-complete' : index === progress.index ? 'is-current' : ''} aria-current={!state.confirmed && index === progress.index ? 'step' : undefined}><span>{index < progress.index || state.confirmed ? <Check size={13} /> : index + 1}</span><span>{step}</span></li>)}</ol>
    <div className={`payment-current ${state.busy ? 'is-working' : ''} ${state.uncertain ? 'is-uncertain' : ''}`} role="status" aria-live="polite" aria-atomic="true"><div className="payment-current-count">{state.confirmed ? 'Completed' : `Step ${progress.index + 1} of ${steps.length}`}{batch ? ` · ${batch}` : ''}</div><h3 key={title}>{title}</h3><p>{body}</p>{state.busy && <span className="payment-working-line" aria-hidden="true" />}</div>
    <details className="payment-how"><summary><ShieldCheck size={16} />What happens behind the scenes?</summary><dl><div><dt>ENS names</dt><dd>Account names are verified before entry. Destinations are checked again before approval and sending.</dd></div>{kind === 'create_distribution' && <div><dt>Chainlink CRE</dt><dd>{cre ? 'The imported local simulation result matched this exact encrypted batch. This is not remote enclave attestation.' : 'This draft uses local compilation. A Chainlink CRE result was not supplied.'}</dd></div>}<div><dt>Private proof</dt><dd>{kind === 'withdraw' || kind === 'shield' ? 'The proof is created on your device. Deposits and withdrawals still expose their wallet, amount and timing.' : 'Your device creates the proof. The sender knows its payment list; private allocation amounts are not published as plain text on chain.'}</dd></div><div><dt>Network visibility</dt><dd>{state.transport === 'relay' ? 'The payment service submits the transaction and pays the network fee. It can see this request and its timing. ' : gasWallet ? `${gasWallet} pays the network fee. ` : 'Your connected wallet pays the network fee. '}The submitting address and timing are public. Network providers can observe your connection.</dd></div></dl></details>
  </section>;
}
