staging-settings:
  user-workflow:
    workflow-name: "null-private-distribution-compiler-v1"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./src/main.ts"
    config-path: "../../.artifacts/cre/config.staging.json"
    secrets-path: "./secrets.yaml"
