import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createServer} from 'node:http';
import {join} from 'node:path';
import {createPublicClient,createWalletClient,http,keccak256,parseAbi} from '../apps/web/node_modules/viem/_esm/index.js';
import {generatePrivateKey,privateKeyToAccount} from '../apps/web/node_modules/viem/_esm/accounts/index.js';
import {foundry} from '../apps/web/node_modules/viem/_esm/chains/index.js';
import {NullLiveClient,type DeploymentManifest,type SecretCheckpoint,type OwnedTreasuryNote} from '../packages/client/src/index.ts';
import {createPrivacyProfile,compileDistribution,authPolicyCommitment,fromHex,toHex,secp256k1} from '../packages/sdk/src/index.ts';
import {createRelayer} from '../services/relayer/src/relay.ts';
import {ProofWorker} from './proof-worker-adapter.mts';
const require=createRequire(import.meta.url), solc=require('solc'), contractsRequire=createRequire(new URL('../packages/contracts/package.json',import.meta.url));
const {poseidonContract}=contractsRequire('circomlibjs');
Object.assign(globalThis,{Worker:ProofWorker});
const port=18546, url=`http://127.0.0.1:${port}`;
// A fresh localhost-only chain. No .env, deployed-site settings or public-network wallets are read.
const anvil=spawn(join(process.env.USERPROFILE!,'.foundry','bin','anvil.exe'),['--host','127.0.0.1','--port',String(port),'--chain-id','31337','--gas-limit','60000000','--silent'],{stdio:'ignore',windowsHide:true});
const rpc=createPublicClient({chain:foundry,transport:http(url,{timeout:30000,retryCount:0})});
const account=privateKeyToAccount(generatePrivateKey());
const wallet=createWalletClient({chain:foundry,account,transport:http(url)});
const checkpoints:SecretCheckpoint[]=[];
const evidence:{checks:string[];transactions:unknown[];[key:string]:unknown}={network:'isolated localhost',chainId:31337,realProofs:true,privyApproval:false,checks:[],transactions:[],completed:false};
let server:ReturnType<typeof createServer>|undefined;
const pass=(label:string)=>{evidence.checks.push(label);console.log(`PASS ${label}`)};
try {
 await new Promise<void>((resolve,reject)=>{anvil.once('error',reject);let tries=0;const check=async()=>{if(anvil.exitCode!==null){reject(Error('Local chain did not start'));return;}try{assert.equal(await rpc.getChainId(),31337);resolve();}catch{if(++tries>30)reject(Error('Local chain unavailable'));else setTimeout(check,300);}};void check();});
 await rpc.request({method:'anvil_setBalance' as any,params:[account.address,'0x3635c9adc5dea00000'] as any});
 const bytecodes=new Map<string,any>();
 async function artifact(name:string){return JSON.parse(await readFile(`contracts/artifacts/${name}.json`,'utf8'));}
 async function deploy(abi:any,bytecode:`0x${string}`,args:any[]=[]){const hash=await wallet.deployContract({abi,bytecode,args,gas:30_000_000n});const receipt=await rpc.waitForTransactionReceipt({hash});assert.equal(receipt.status,'success');assert.ok(receipt.contractAddress);evidence.transactions.push({action:'deploy',hash});return receipt.contractAddress;}
 async function deployArtifact(name:string):Promise<`0x${string}`>{if(bytecodes.has(name))return bytecodes.get(name);const a=await artifact(name);let bytecode=a.bytecode;for(const[source,refs]of Object.entries(a.linkReferences) as any){for(const[lib,positions]of Object.entries(refs) as any){const address=await deployArtifact(`by-source/${source}/${lib}`);for(const pos of positions)bytecode=bytecode.slice(0,2+pos.start*2)+address.slice(2).toLowerCase()+bytecode.slice(2+(pos.start+pos.length)*2);}}const address=await deploy(a.abi,bytecode);bytecodes.set(name,address);return address;}
 const tokenSource=`pragma solidity 0.8.28; contract FlowToken { uint8 public constant decimals=6; mapping(address=>uint256) public balanceOf; mapping(address=>mapping(address=>uint256)) public allowance; bool public failTransfers; function mint(address to,uint256 n) external {balanceOf[to]+=n;} function setFail(bool v) external {failTransfers=v;} function approve(address to,uint256 n) external returns(bool){allowance[msg.sender][to]=n;return true;} function transferFrom(address from,address to,uint256 n) external returns(bool){require(allowance[from][msg.sender]>=n);allowance[from][msg.sender]-=n;return move(from,to,n);} function transfer(address to,uint256 n) external returns(bool){if(failTransfers)return false;return move(msg.sender,to,n);} function move(address from,address to,uint256 n) internal returns(bool){require(balanceOf[from]>=n);balanceOf[from]-=n;balanceOf[to]+=n;return true;} }`;
 const out=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources:{'FlowToken.sol':{content:tokenSource}},settings:{evmVersion:'cancun',optimizer:{enabled:true,runs:200},outputSelection:{'*':{'*':['abi','evm.bytecode.object']}}}})));
 const token=out.contracts['FlowToken.sol'].FlowToken, asset=await deploy(token.abi,`0x${token.evm.bytecode.object}`);
 const poseidon3=await deploy(poseidonContract.generateABI(3),poseidonContract.createCode(3));
 const registryArtifact=await artifact('NullAuthRegistry');const nullAuthRegistry=await deploy(registryArtifact.abi,registryArtifact.bytecode,[poseidon3]);
 const shieldVerifier=await deployArtifact('ShieldVerifier'), createDistributionVerifier=await deployArtifact('CreateDistributionVerifier'), claimVerifier=await deployArtifact('ClaimVerifier'), withdrawVerifier=await deployArtifact('WithdrawVerifier');
 const partialWithdrawVerifier=await deployArtifact('PartialWithdrawVerifier');
 const poolArtifact=await artifact('NullPoolV3');const nullPool=await deploy(poolArtifact.abi,poolArtifact.bytecode,[asset,poseidon3,nullAuthRegistry,shieldVerifier,createDistributionVerifier,claimVerifier,withdrawVerifier,partialWithdrawVerifier]);
 const contracts={nullPool,nullAuthRegistry,poseidon3,shieldVerifier,createDistributionVerifier,claimVerifier,withdrawVerifier,partialWithdrawVerifier};
 const codeHashes:any={};for(const[name,address]of Object.entries({...contracts,asset}))codeHashes[name]=keccak256((await rpc.getCode({address}))!);
 const compiledManifest=JSON.parse(await readFile('circuits/target/manifest.json','utf8'));
 const manifest:DeploymentManifest={status:'deployed',protocolVersion:'0.3.0',chainId:31337,deploymentBlock:0,asset:{symbol:'USDC',decimals:6,address:asset},contracts,codeHashes,build:{noir:'1.0.0-beta.22',barretenberg:'5.0.0-nightly.20260522',circuitArtifacts:compiledManifest.circuits},security:{networkScope:'testnet-only',withdrawalsImplemented:true,partialWithdrawalsImplemented:true,audited:false}};
 const relayKey=generatePrivateKey();const relay=createRelayer({manifest,rpcUrl:url,privateKey:relayKey,maxGas:10_000_000n});await rpc.request({method:'anvil_setBalance' as any,params:[relay.account,'0x3635c9adc5dea00000'] as any});
 server=createServer(async(req,res)=>{if(req.url==='/relay' && req.method==='POST'){try{const chunks=[];for await(const chunk of req)chunks.push(chunk);const result=await relay.relay(JSON.parse(Buffer.concat(chunks).toString()));res.setHeader('content-type','application/json');res.end(JSON.stringify(result));}catch{res.writeHead(422).end(JSON.stringify({code:'NULL_RELAY_REJECTED'}));}return;}const kind=req.url?.match(/^\/circuits\/(shield|create_distribution|claim|withdraw|withdraw_partial)\.json$/)?.[1];if(!kind){res.writeHead(404).end();return;}res.setHeader('content-type','application/json');res.end(await readFile(`circuits/target/${kind}.json`));});await new Promise<void>(r=>server!.listen(0,'127.0.0.1',r));
 const artifactBaseUrl=`http://127.0.0.1:${(server.address() as any).port}`;
 const client=new NullLiveClient({manifest,rpcUrls:[url],artifactBaseUrl,confirmations:1,maxGas:10_000_000n,persistLocalSecret:async cp=>{checkpoints.push(structuredClone(cp));}});
 const progress={onProgress:(stage:string)=>console.log(stage),onTransactionSubmitted:(tx:unknown)=>{evidence.transactions.push(tx);}};
 const identity=createPrivacyProfile(), signer=generatePrivateKey();const policy={signerPublicKey:toHex(secp256k1.getPublicKey(fromHex(signer),true)),policyMetadata:1n,registrationBlinder:2n};
 const authorize=async(intent:{digest:`0x${string}`})=>toHex(secp256k1.sign(fromHex(intent.digest),fromHex(signer),{prehash:false,lowS:true}).toCompactRawBytes());
 async function tokenWrite(functionName:string,args:any[]){const hash=await wallet.writeContract({address:asset,abi:token.abi,functionName,args});assert.equal((await rpc.waitForTransactionReceipt({hash})).status,'success');}
 const balance=(address:`0x${string}`)=>rpc.readContract({address:asset,abi:token.abi,functionName:'balanceOf',args:[address]}) as Promise<bigint>;
 await tokenWrite('mint',[account.address,1_000_000n]);
 await client.registerPolicy({opening:policy,wallet,persistLocalPolicy:async()=>{},...progress});
 const deposit=await client.prepareShield({amountAtomic:1_000_000n,policyCommitment:authPolicyCommitment(policy),acknowledgePublicDeposit:true,...progress});
 const funded=await client.submit(deposit,{mode:'wallet',wallet},progress);assert.equal(await balance(nullPool),1_000_000n);pass('deposit backed exactly by token balance');
 const compiled=await compileDistribution({context:client.context,recipients:[{employeeRef:'Local flow recipient',amountAtomic:600_000n,stealthMetaAddress:identity.profile.stealthMetaAddress}]});
 const payment=await client.prepareDistribution({compiled,treasuryNotes:[funded.note as OwnedTreasuryNote],authPolicy:policy,authorize,...progress});
 const paid=await client.submit(payment,{mode:'wallet',wallet},progress);assert.equal(paid.note.amountAtomic,400_000n);pass('organization-approved distribution and exact private change');
 const found=await client.discover({keys:identity.keys,...progress});assert.equal(found.length,1);assert.equal(found[0].amountAtomic,600_000n);
 const claim=await client.prepareClaim({allocation:found[0],...progress});await client.submit(claim,{mode:'wallet',wallet},progress);pass('stealth discovery and claim with real proof');
 const restored=await client.recoverPrivateNotes({keys:identity.keys,checkpoints});assert.equal(restored.length,1);assert.equal(restored[0].amountAtomic,600_000n);pass('recipient recovery from original keys and chain history');
 const differentIdentity=createPrivacyProfile();
 const backupRestored=await client.recoverPrivateNotes({keys:differentIdentity.keys,checkpoints});assert.deepEqual(backupRestored.map(note=>note.commitment),restored.map(note=>note.commitment));pass('funds backup recovers collected notes without the original Payment ID');
 const receiver=privateKeyToAccount(generatePrivateKey()).address;
 const partial=await client.prepareWithdrawal({note:restored[0],recipient:receiver,amountAtomic:250_000n,acknowledgePublicWithdrawal:true,...progress});
 assert.equal(partial.publicOperation.method,'withdrawPartial');
 const stolen=[...partial.publicOperation.publicInputs];stolen[6]=('0x'+BigInt(account.address).toString(16).padStart(64,'0')) as any;
 await assert.rejects(()=>rpc.simulateContract({address:nullPool,abi:poolArtifact.abi,functionName:'withdrawPartial',args:[partial.publicOperation.proof,stolen]}));
 const inflated=[...partial.publicOperation.publicInputs];inflated[7]=('0x'+(250_001n).toString(16).padStart(64,'0')) as any;
 await assert.rejects(()=>rpc.simulateContract({address:nullPool,abi:poolArtifact.abi,functionName:'withdrawPartial',args:[partial.publicOperation.proof,inflated]}));
 await tokenWrite('setFail',[true]);
 await assert.rejects(()=>client.submit(partial,{mode:'wallet',wallet},progress));
 assert.equal(await balance(nullPool),1_000_000n);
 assert.equal((await client.recoverPrivateNotes({keys:identity.keys,checkpoints}))[0].amountAtomic,600_000n);
 await tokenWrite('setFail',[false]);
 const partialResult=await client.submit(partial,{mode:'sponsored',send:async operation=>(await relay.relay(operation)).transactionHash},progress);
 assert.equal(partialResult.withdrawal?.amountAtomic,250_000n);assert.equal(partialResult.note.amountAtomic,350_000n);
 assert.equal(await balance(receiver),250_000n);assert.equal(await balance(nullPool),750_000n);
 assert.equal((await rpc.getTransaction({hash:partialResult.transactionHash})).from.toLowerCase(),relay.account.toLowerCase());
 const remaining=await client.recoverPrivateNotes({keys:differentIdentity.keys,checkpoints});assert.equal(remaining.length,1);assert.equal(remaining[0].amountAtomic,350_000n);
 assert.equal((await client.reconcile(partial)).status,'confirmed');
 await assert.rejects(()=>rpc.simulateContract({address:nullPool,abi:poolArtifact.abi,functionName:'withdrawPartial',args:[partial.publicOperation.proof,partial.publicOperation.publicInputs]}));
 restored[0]=remaining[0];
 pass('partial withdrawal: exact public amount, hidden change, sponsor-funded gas, encrypted recovery, no double spend, no recipient or amount substitution');
 const withdrawal=await client.prepareWithdrawal({note:restored[0],recipient:receiver,acknowledgePublicWithdrawal:true,...progress});
 const tampered=[...withdrawal.publicOperation.publicInputs];tampered[6]=`0x${BigInt(account.address).toString(16).padStart(64,'0')}`;
 await assert.rejects(()=>rpc.simulateContract({address:nullPool,abi:poolArtifact.abi,functionName:'withdraw',args:[withdrawal.publicOperation.proof,tampered]}));pass('recipient substitution rejected by deployed proof verifier');
 await tokenWrite('setFail',[true]);await assert.rejects(()=>client.submit(withdrawal,{mode:'wallet',wallet},progress));assert.equal(await balance(nullPool),750_000n);assert.equal((await client.recoverPrivateNotes({keys:identity.keys,checkpoints})).length,1);pass('failed transfer leaves note unspent and funds recoverable');
 await tokenWrite('setFail',[false]);
 const withdrawn=await client.submit(withdrawal,{mode:'relay',url:artifactBaseUrl+'/relay'},progress);assert.equal((await rpc.getTransaction({hash:withdrawn.transactionHash})).from.toLowerCase(),relay.account.toLowerCase());pass('independent relayer broadcasts without recipient gas funding');assert.equal(await balance(receiver),600_000n);assert.equal(await balance(nullPool),400_000n);assert.equal((await client.recoverPrivateNotes({keys:identity.keys,checkpoints})).length,0);pass('withdrawal paid exact amount and removed spent balance after recovery');
 assert.equal((await client.recoverPrivateNotes({keys:differentIdentity.keys,checkpoints})).length,0);pass('old funds backup cannot restore a withdrawn balance');
 const reconciliation=await client.reconcile(withdrawal,undefined);assert.equal(reconciliation.status,'confirmed');pass('withdrawal reconciles from public history without a returned transaction hash');
 await assert.rejects(()=>client.submit(withdrawal,{mode:'wallet',wallet}));await assert.rejects(()=>rpc.simulateContract({address:nullPool,abi:poolArtifact.abi,functionName:'withdraw',args:[withdrawal.publicOperation.proof,withdrawal.publicOperation.publicInputs]}));pass('double withdrawal rejected by client and contract');
 const treasury=(await client.recoverTreasuryNotes(checkpoints)).filter(x=>!x.spent&&x.note.amountAtomic>0n);assert.equal(treasury.length,1);
 await assert.rejects(()=>client.prepareWithdrawal({note:treasury[0].note,recipient:account.address,acknowledgePublicWithdrawal:true}));pass('treasury exit cannot bypass organization approval');
 const refund=await client.prepareWithdrawal({note:treasury[0].note,recipient:account.address,authPolicy:policy,authorize,acknowledgePublicWithdrawal:true,...progress});await client.submit(refund,{mode:'wallet',wallet},progress);assert.equal(await balance(account.address),400_000n);assert.equal(await balance(nullPool),0n);pass('approved treasury refund and zero remaining pool liabilities');
 assert.equal(await balance(account.address)+await balance(receiver),1_000_000n);evidence.buildIntegrity=JSON.parse(await readFile('contracts/artifacts/build-integrity.json','utf8')).sources;evidence.circuitArtifacts=compiledManifest.circuits;evidence.completed=true;pass('full conservation: 1 USDC deposited = 0.6 received + 0.4 refunded');
 for(const tx of evidence.transactions as {hash?:`0x${string}`;action?:string;gasUsed?:string}[]){if(tx.hash && tx.action!=='deploy')tx.gasUsed=(await rpc.getTransactionReceipt({hash:tx.hash})).gasUsed.toString();}
} catch(error) { console.error('FAIL local payment flow:',error instanceof Error?error.name:'unknown');evidence.failure=error instanceof Error?error.message.split('\n')[0].slice(0,200):'unknown';process.exitCode=1;
} finally {await mkdir('.artifacts',{recursive:true});await writeFile('.artifacts/payment-flow-v3-local.json',JSON.stringify(evidence,null,2));server?.closeAllConnections();server?.close();anvil.kill();}
