import { useState } from 'react';
import { ArrowDownLeft, ArrowRight, ArrowUpRight, Check, ChevronRight, Circle, FileText, Inbox, LockKeyhole, Plus, Search, Send, Shield, ShieldCheck, SlidersHorizontal, Wallet } from 'lucide-react';
import { useStore, type Distribution } from '../lib/store';
import { config } from '../lib/config';
import { amount, date, money, short, stringify, download } from '../lib/format';
import { Badge, Button, EmptyState, KeyValue, Modal, Notice, PageHeader, SectionTitle } from '../components/ui';

export function DistributionTable({ items, compact = false }: { items: Distribution[]; compact?: boolean }) {
  const store = useStore(); const [selected, setSelected] = useState<Distribution | null>(null);
  return <>{items.length ? <div className="table-scroll"><table className="distribution-table"><thead><tr><th>Distribution</th><th>Recipients</th><th>Total amount</th><th>Status</th>{!compact && <th>Created</th>}<th><span className="sr-only">Open</span></th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><button className="table-title" onClick={() => ['Published locally', 'Confirmed'].includes(item.status) ? setSelected(item) : store.editDistribution(item.id)}><span className="distribution-icon"><Send size={17} strokeWidth={1.6} /></span><span><strong>{item.name}</strong><small>{item.category}</small></span></button></td><td><span className="recipient-count">{item.recipients.length}<span> / 8 slots</span></span></td><td className="numeric"><strong>{store.hideBalances ? '••••••' : money(item.recipients.reduce((sum, row) => sum + amount(row.amount), 0n))}</strong><span className="currency">USDC</span></td><td><Badge tone={['Published locally', 'Confirmed'].includes(item.status) ? 'success' : item.status === 'Prepared' ? 'purple' : 'neutral'} dot>{item.status === 'Published locally' ? 'Local publication' : item.status}</Badge></td>{!compact && <td className="muted">{date(item.createdAt)}</td>}<td><button className="icon-button" aria-label={`Open ${item.name}`} onClick={() => ['Published locally', 'Confirmed'].includes(item.status) ? setSelected(item) : store.editDistribution(item.id)}><ChevronRight size={16} /></button></td></tr>)}</tbody></table></div> : <EmptyState icon={Send} title="Your next distribution starts here" description="Prepare a private payout for up to eight recipients. Names and amounts stay in your browser." action={<Button icon={Plus} onClick={() => store.editDistribution(null)}>Create distribution</Button>} />}
  <Modal title={selected?.name || 'Distribution'} description={selected?.status === 'Confirmed' ? 'Confirmed Sepolia distribution' : 'Local cryptographic artifact · No chain transaction'} open={!!selected} onClose={() => setSelected(null)}>{selected && <><div className="detail-list"><KeyValue label="Status"><Badge tone="success">{selected.status}</Badge></KeyValue><KeyValue label="Encrypted delivery">8 fixed-size envelopes</KeyValue><KeyValue label="Commitment"><code>{short(String(selected.compiled?.commitment || ''), 12)}</code></KeyValue><KeyValue label="Private total">{money(selected.recipients.reduce((sum, row) => sum + amount(row.amount), 0n), true)} USDC</KeyValue></div><Notice>{selected.status === 'Confirmed' ? 'This distribution was confirmed on Sepolia. Its encrypted envelopes can be discovered by recipients from public history.' : 'Encrypted delivery is available in your local inbox. Live publication requires organization authorization, a local proof, and a verified deployment.'}</Notice>{selected.transactionHash && <a className="text-link" href={`https://sepolia.etherscan.io/tx/${selected.transactionHash}`} target="_blank" rel="noreferrer">View confirmed transaction<ArrowUpRight size={14} /></a>}<div className="modal-actions"><Button variant="secondary" onClick={() => download('null-public-distribution.json', stringify(selected.compiled?.publicBundle))}>Export public bundle</Button><Button onClick={() => { setSelected(null); store.navigate('inbox'); }}>Open private inbox<ArrowRight size={15} /></Button></div></>}</Modal></>;
}

export function Overview() {
  const store = useStore();
  const drafts = store.distributions.filter(item => !['Published locally', 'Confirmed'].includes(item.status));
  const published = store.distributions.filter(item => ['Published locally', 'Confirmed'].includes(item.status));
  const pending = drafts.reduce((total, item) => total + item.recipients.reduce((sum, row) => sum + amount(row.amount), 0n), 0n);
  return <>
    <PageHeader title="Private by default." description="Your treasury, distributions, and the details that stay yours." action={<Button icon={Plus} onClick={() => store.editDistribution(null)}>New distribution</Button>} />
    {store.mode === 'testnet' && <Notice tone="warning">{config.poolAddress ? 'Sepolia contract configuration is loaded. Connect your wallet and import your treasury policy to prepare live operations. Each operation verifies the deployment before proving.' : 'This workspace uses Sepolia. Configure a verified deployment and proof artifacts to enable live funds. Local sample activity is hidden.'}</Notice>}
    <div className="overview-financials">
      <div className="treasury-overview"><div className="balance-label"><span><ShieldCheck size={17} />Shielded treasury</span><Badge tone="purple"><LockKeyhole size={11} />{store.mode === 'sandbox' ? 'Sandbox balance' : store.treasuryReady ? 'Recovered snapshot' : 'Not recovered'}</Badge></div><div className="balance-value">{!store.treasuryReady ? '—' : store.hideBalances ? '••••••' : money(store.treasury)}<span>USDC</span></div><div className="balance-bottom"><p><span className="status-dot" />{store.mode === 'sandbox' ? 'Available for local distributions' : 'Connect a verified treasury'}</p><button className="text-link" onClick={() => store.navigate('treasury')}>Manage treasury<ArrowUpRight size={14} /></button></div></div>
      <div className="financial-side"><div><span className="metric-label">In draft distributions</span><strong className="metric-value">{store.hideBalances ? '••••••' : money(pending)}<small>USDC</small></strong><p>{drafts.length} drafts in your workspace</p></div><div><span className="metric-label">Published distributions</span><strong className="metric-value">{published.length.toString().padStart(2, '0')}<span className="mini-lock"><LockKeyhole size={15} /></span></strong><p>{store.mode === 'sandbox' ? 'In this local session' : published.length ? 'Confirmed in this session' : 'No confirmed chain data yet'}</p></div></div>
    </div>
    <div className="workspace-callout"><span className="callout-symbol"><Shield size={22} strokeWidth={1.5} /></span><div><strong>Built to keep the details private.</strong><p>Eight encrypted slots. Local discovery. Your recipients’ information stays off the public record.</p></div><button className="text-link" onClick={() => store.navigate('inspector')}>See what’s visible<ArrowRight size={15} /></button></div>
    <section className="section-block"><SectionTitle title="Recent distributions" caption="Prepare, review, and send from one private workspace." action={<button className="text-link" onClick={() => store.navigate('distributions')}>View all<ArrowRight size={14} /></button>} /><div className="table-panel"><DistributionTable items={store.distributions.slice(0, 4)} compact /><div className="table-footer"><LockKeyhole size={13} /><span>Names and amounts are visible only in this local session.</span><span>8-slot protocol</span></div></div></section>
    <div className="overview-bottom"><section className="activity-section"><SectionTitle title="Workspace activity" action={<Badge>{store.mode === 'sandbox' ? 'Local' : 'Testnet'}</Badge>} />{store.activities.length ? <div className="activity-list">{store.activities.slice(0, 4).map(item => <div className="activity-row" key={item.id}><span className="activity-icon">{item.type === 'shield' ? <ArrowDownLeft size={16} /> : item.type === 'distribution' ? <Send size={16} /> : item.type === 'claim' ? <LockKeyhole size={16} /> : <Check size={16} />}</span><div><strong>{item.title}</strong><p>{item.detail}</p></div><time>{new Date(item.createdAt).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })}</time></div>)}</div> : <p className="subtle-empty">Confirmed network activity will appear here when connected.</p>}</section><section className="quick-start"><div className="section-title"><h2>A quieter way to pay.</h2><span className="brand-symbol small" /></div><p>Try the full recipient experience with a local distribution.</p><button onClick={() => store.editDistribution(store.distributions[0]?.id || null)}><span className="step-number">1</span><span>Prepare a distribution</span><ArrowUpRight size={15} /></button><button onClick={() => store.navigate('inbox')}><span className="step-number">2</span><span>Discover your allocation</span><ArrowUpRight size={15} /></button><button onClick={() => store.navigate('balance')}><span className="step-number">3</span><span>Keep your balance private</span><ArrowUpRight size={15} /></button></section></div>
  </>;
}

export function Distributions() {
  const store = useStore(); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('All distributions');
  const filtered = store.distributions.filter(item => item.name.toLowerCase().includes(search.toLowerCase()) && (filter === 'All distributions' || (filter === 'Drafts' ? item.status === 'Draft' : filter === 'Prepared' ? item.status === 'Prepared' : ['Published locally', 'Confirmed'].includes(item.status))));
  return <><PageHeader title="Distributions" description="Private payouts, thoughtfully organized." action={<Button icon={Plus} onClick={() => store.editDistribution(null)}>New distribution</Button>} /><div className="list-toolbar"><div className="tabs">{['All distributions', 'Drafts', 'Prepared', 'Published'].map(tab => <button key={tab} className={tab === filter ? 'selected' : ''} onClick={() => setFilter(tab)}>{tab}{tab === 'All distributions' && <span>{store.distributions.length}</span>}</button>)}</div><label className="search-field"><Search size={16} /><input aria-label="Search distributions" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search distributions…" /></label></div><div className="table-panel">{filtered.length || !search && filter === 'All distributions' ? <DistributionTable items={filtered} /> : <EmptyState icon={Search} title="No matching distributions" description="Try a different name or show all distributions." action={<Button variant="secondary" onClick={() => { setSearch(''); setFilter('All distributions'); }}>Clear filters</Button>} />}<div className="table-footer"><span>{filtered.length} distribution{filtered.length !== 1 ? 's' : ''}</span><span>Amounts are private to your workspace</span></div></div></>;
}
