import { useState } from 'react';
import { ArrowDownLeft, ArrowRight, Check, Download, Globe, LockKeyhole, Shield, Wallet } from 'lucide-react';
import { useStore } from '../lib/store';
import { useAccount } from '../lib/account';
import { download, stringify } from '../lib/format';
import { Badge, Button, Notice, PageHeader, SectionTitle } from '../components/ui';

export function Inspector() {
  const store = useStore(); const [view, setView] = useState<'distribution' | 'claim'>('distribution');
  const compiled = store.distributions.find(item => item.compiled)?.compiled;
  const claimNote = store.notes[0];
  const publicPayload = view === 'distribution' ? compiled?.publicBundle : claimNote ? { noteCommitment: claimNote.commitment, claimNullifier: claimNote.allocationId, source: 'local sandbox — no proof or chain transaction' } : undefined;
  const visible = view === 'distribution' ? ['Distribution commitment', 'Eight encrypted envelopes', 'Ephemeral delivery keys and view tags', 'Proof and input nullifiers in a live transaction'] : ['Claim nullifier', 'Private-note commitment', 'Global distribution root', 'Proof and broadcaster in a live transaction'];
  const hidden = ['Recipient names and identifiers', 'Recipient wallet addresses', 'One-time stealth public key', 'Individual allocation amounts', ...(view === 'claim' ? ['Allocation position', 'Specific source distribution'] : [])];
  return <><PageHeader title="Privacy inspector" description="Know exactly what becomes public—and what stays yours." action={<Badge tone="purple"><Shield size={12} />Protocol boundaries</Badge>} /><div className="tabs inspector-tabs"><button className={view === 'distribution' ? 'selected' : ''} onClick={() => setView('distribution')}>Distribution</button><button className={view === 'claim' ? 'selected' : ''} onClick={() => setView('claim')}>Private claim</button></div><div className="privacy-compare"><section className="privacy-public"><div className="privacy-section-header"><Globe size={21} /><Badge>Public chain data</Badge></div><h2>The public record.</h2><p>What a chain observer can read in a live protocol transaction.</p><ul>{visible.map(item => <li key={item}><Check size={15} />{item}</li>)}</ul></section><section className="privacy-hidden"><div className="privacy-section-header"><LockKeyhole size={21} /><Badge tone="purple">Inside the private zone</Badge></div><h2>The details stay yours.</h2><p>Committed or encrypted, with entitlement proved in zero knowledge.</p><ul>{hidden.map(item => <li key={item}><LockKeyhole size={14} />{item}</li>)}</ul></section></div><Notice>The private-zone guarantees depend on the complete circuits, verified artifacts, and deployed contracts. The local sandbox demonstrates encrypted delivery and commitments; it does not establish live chain privacy.</Notice><section className="section-block"><SectionTitle title="Public payload" caption={publicPayload ? 'Actual public fields from this local session.' : 'Prepare a distribution or claim locally to inspect its public artifact.'} action={publicPayload ? <Button variant="secondary" icon={Download} onClick={() => download('null-public-artifact.json', stringify(publicPayload))}>Export</Button> : undefined} /><div className="code-panel"><div className="code-panel-header"><span>{view === 'distribution' ? 'distribution.public.json' : 'claim.local.json'}</span><Badge>{publicPayload ? 'Local artifact' : 'No artifact yet'}</Badge></div><pre>{publicPayload ? stringify(publicPayload) : '// No prepared artifact in this session.\n// Create a distribution to inspect real encrypted fields.\n// Private witnesses are never included in this view.'}</pre></div></section><div className="boundary-list"><h2>Privacy has boundaries.</h2><div><ArrowDownLeft size={19} /><span><strong>Public entry and exit</strong><p>Deposits and public withdrawals reveal their wallet, amount, and timing.</p></span></div><div><Globe size={19} /><span><strong>Network and timing metadata</strong><p>RPCs and relayers can observe requests and IP metadata. NULL does not provide network anonymity.</p></span></div><div><Wallet size={19} /><span><strong>Employer knowledge</strong><p>The sender knows their own recipients and intended allocations.</p></span></div></div></>;
}

export { Protocol } from './Protocol';

export { AccountSettings as Settings } from '../components/AccountSettings';

export function About() {
  const store = useStore(); const { profile } = useAccount();
  const individual = profile?.type === 'individual';
  return <><PageHeader title="Help" description="Get started and keep access to your payments." />
    <section><h2>{individual ? 'Receive a payment' : 'Send a payment'}</h2>
      <ol className="help-steps">{(individual ? ['Save your backup, link an ENS payment name in your inbox, then share that name.', 'Check your inbox for new payments.', 'Open a payment, review it, and choose Collect payment.', 'Save a backup in Settings before reloading or signing out.'] : ['Open Funds to add money or restore your balance.', 'Choose New payment, then add each recipient’s ENS payment name and amount.', 'Review the names and amounts, then send the payment.', 'Save a backup in Settings and keep the backup files created when adding funds or sending payments.']).map(step => <li key={step}>{step}</li>)}</ol>
      <Button onClick={() => individual ? store.navigate('inbox') : store.editDistribution(null)}>{individual ? 'Open inbox' : 'New payment'}<ArrowRight size={16} /></Button>
    </section>
    <details className="progressive-details"><summary>What is a Payment ID?</summary><p>It contains the public keys behind your ENS payment name. Link it to your name in the inbox so senders can find your payment destination. It is not a wallet address. Your backup and its password must stay private.</p></details>
    <details className="progressive-details"><summary>How do I keep access to my payments?</summary><p>Choose Save backup under Payment ID backup in Settings. Keep the file and password separately. Signing in alone does not restore your Payment ID, drafts, or balances. To return to the same Payment ID, choose Restore backup, then check your inbox. Keep the separate funds backups created when adding funds, sending, or collecting payments. Use Restore balance to restore those funds.</p></details>
    <details className="progressive-details"><summary>Can I withdraw or use real money?</summary><p>Use test tokens only; NULL has not had an independent security review. Withdrawals require the new withdrawal-capable pool. In Balance or Funds, choose Withdraw, select a note and review the receiving address. The full note amount is sent publicly. The old immutable pool has no exit function.</p></details>
    <details className="progressive-details"><summary>How do I receive with an ENS name?</summary><p>In your inbox, choose Link ENS name. Check a Sepolia name you own, save your backup, then link your Payment ID with your wallet. The name and Payment ID are public. Every recipient needs a linked ENS name for new payments. An expired or changed name blocks new payments until checked again; your existing funds remain accessible with your backup.</p></details>
    <details className="progressive-details"><summary>What can other people see?</summary><p>Deposits show the sending wallet, amount, and time publicly. The sender knows who they pay and how much. Service providers may see connection details, such as your IP address. NULL does not make all activity anonymous.</p></details>
    {!individual && <details className="progressive-details"><summary>Why can’t I send for my organization?</summary><p>Choosing Organization or entering its name does not give you permission to send. Your organization must approve your account and payments separately. Contact your administrator if you need access.</p></details>}
    <div className="help-links"><button className="text-link" onClick={() => store.navigate('settings')}>Open settings<ArrowRight size={14} /></button></div>
  </>;
}
